engines:
  govet:
    enabled: true
  golint:
    enabled: true
    exclude_paths:
      - "vm/instruction.go"
      - "vm/vm.go"
  gofmt:
    enabled: true
    exclude_paths:
      - "vm/instruction.go"
      - "vm/vm.go"

exclude_paths:
  - "Godeps"
  - "test_fixtures"
  - "vendor"

ratings:
  paths:
    - "**.go"