// Code generated by "stringer -type=InstructionAction"; DO NOT EDIT.

package bytecode

import "strconv"

const _InstructionAction_name = "GetLocalGetConstantGetInstanceVariableSetLocalSetConstantSetInstanceVariablePutBooleanPutStringPutFloatPutSelfPutObjectPutNullNewArrayExpandArraySplatArrayNewHashNewRangeBranchUnlessBranchIfJumpBreakDefMethodDefSingletonMethodDefClassSendInvokeBlockGetBlockPopDupLeave"

var _InstructionAction_index = [...]uint16{0, 8, 19, 38, 46, 57, 76, 86, 95, 103, 110, 119, 126, 134, 145, 155, 162, 170, 182, 190, 194, 199, 208, 226, 234, 238, 249, 257, 260, 263, 268}

func (i InstructionAction) String() string {
	i -= 1
	if i >= InstructionAction(len(_InstructionAction_index)-1) {
		return "InstructionAction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _InstructionAction_name[_InstructionAction_index[i]:_InstructionAction_index[i+1]]
}
