name: goby-lang
version: git
summary: A new language helps you develop microservices
description: |
  Goby is an object-oriented interpreter language deeply inspired by Ruby as
  well as its core implementation by 100% pure Go. Moreover, it has standard
  libraries to provide several features such as the Plugin system.

grade: stable
confinement: classic

apps:
  goby:
    environment:
      GOBY_ROOT: $SNAP
    command: bin/goby

parts:
  goby:
    source: .
    plugin: go
    go-importpath: github.com/goby-lang/goby
    install:
      cp -R lib/ $SNAPCRAFT_PART_INSTALL
    after: [go]
  go:
    source-tag: go1.9
