package classes

const (
	ObjectClass     = "Object"
	ClassClass      = "Class"
	ModuleClass     = "Module"
	IntegerClass    = "Integer"
	FloatClass      = "Float"
	StringClass     = "String"
	ArrayClass      = "Array"
	HashClass       = "Hash"
	BooleanClass    = "Boolean"
	NullClass       = "Null"
	ChannelClass    = "Channel"
	RangeClass      = "Range"
	MethodClass     = "Method"
	PluginClass     = "Plugin"
	GoObjectClass   = "GoObject"
	FileClass       = "File"
	RegexpClass     = "Regexp"
	MatchDataClass  = "MatchData"
	GoMapClass      = "GoMap"
	DecimalClass    = "Decimal"
	BlockClass      = "Block"
	EnumeratorClass = "Enumerator"
)
